import Header from "@/components/header"
import Footer from "@/components/footer"
import "./global.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <body>
        <div className="blogAppContainer">
          <div className="blogAppHeaderCls">
            <Header />
          </div>
          <div className="blogAppBodyContainer">
            {children}
          </div>
          <div className="blogAppFooterContainerCls">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
